### PR TITLE
Implemented S3 Redirects

### LINKED ISSUE #129: Patch to set S3 redirects?
I've wound up monkey patching Middleman & s3sync to support setting `x-amz-website-redirect-location` on resources configured with the `redirect` method in `config.rb`:https://github.com/wossname/woss.name/blob/master/helpers/s3_redirects.rb. Is that the sort of thing I should be tidying up into a pull request at some point?

### PR DESCRIPTION
**Pull request by matiasgarciaisaia**
Fixes #129

> ⚠️⚠️ **Warning**: please test.⚠️⚠️

I don't have a working MM4 instance, so this is a cherry-pick from [my MM3 version](https://github.com/matiasgarciaisaia/middleman-s3_sync/tree/redirect-resource) - and _that one_ works.

I've almost shamelessly copied what @mathie shared on #129 - his [`s3_redirects.rb`](https://github.com/wossname/woss.name/blob/c1fbed24bfffd41cdb394578d23ab81279f8f2f8/helpers/s3_redirects.rb) file.

See http://docs.aws.amazon.com/AmazonS3/latest/dev/how-to-page-redirect.html

### CODE REVIEW

**Comment by fredjean** [comment]
@matiasgarciaisaia Thank you for the PR! I'll have a look this weekend.

**Comment by fredjean** [comment]
LGTM. I'll test locally before pushing a new version of the gem.

**Comment by fredjean** [comment]
It is unfortunately not working. I'll see if I can find an easy fix though.

**Comment by matiasgarciaisaia** [comment]
Hi @fredjean!

You're right - this wasn't working. After _lots_ of debugging (and even applying [your extra commit](https://github.com/fredjean/middleman-s3_sync/commit/5f8921973a84d1ed4ca74debc77dd61dfbebb19b)), I found I had to manually call `sitemap.ensure_resource_list_updated!` after applying the `redirect`s. It _may_ be relevant that I was doing that on a `ready` block in my `config.rb` - I'm redirecting blogposts and a few other pages, so I needed the `sitemap` to be fully populated before doing the redirects.

Calling `sitemap.ensure_resource_list_updated!` after the last `redirect` worked. I'm not sure if there's a best way to do this - or if this applies to any use case that _doesn't_ add `redirect`s on the `ready` block.

**Pull request merged**
